project_id = "uywvebyqbyywnwqjjdto"

[functions.process-email-queue]
verify_jwt = true

[functions.pesapal-checkout]
verify_jwt = false

[functions.pesapal-ipn]
verify_jwt = false

[functions.manual-checkout]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = true

[functions.send-ai-lead-notification]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false
