import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Check, ExternalLink, FileUp, Link2, MessageSquareWarning, RotateCcw, X } from "lucide-react";
import { toast } from "sonner";
import Seo from "@/components/Seo"; import AppShell from "@/components/system/AppShell"; import { PageHeader, StatusChip } from "@/components/system"; import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client"; import { useMyRoles } from "@/hooks/useMyRoles";
import { evidenceUrl, loadLeadershipTask, personName, taskStatusLabel, type LeadershipTask, type StaffPerson, type TaskActivity, type TaskAssignee, type TaskEvidence } from "@/lib/leadershipTasks";
const field="field text-sm";
export default function LeadershipTaskPage(){const{id}=useParams();const nav=useNavigate();const roles=useMyRoles();const[task,setTask]=useState<LeadershipTask|null>(null);const[assignees,setAssignees]=useState<TaskAssignee[]>([]);const[evidence,setEvidence]=useState<TaskEvidence[]>([]);const[activity,setActivity]=useState<TaskActivity[]>([]);const[people,setPeople]=useState<StaffPerson[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[link,setLink]=useState("");
  const load=useCallback(async()=>{if(!id)return;setLoading(true);try{const d=await loadLeadershipTask(id);setTask(d.task);setAssignees(d.assignees);setEvidence(d.evidence);setActivity(d.activity);setPeople(d.people);}catch(e){toast.error(e instanceof Error?e.message:"Could not load task");}finally{setLoading(false);}},[id]);useEffect(()=>{load();},[load]);
  if(loading)return <AppShell><p className="text-sm text-ink-soft">Loading assigned work…</p></AppShell>;if(!task||!id)return <AppShell><p className="text-sm text-ink-soft">This task is unavailable.</p></AppShell>;
  const mine=assignees.some((a)=>a.user_id===roles.userId);const decider=task.assigned_by===roles.userId||roles.has("admin");const closed=["accepted","cancelled"].includes(task.status);
  const act=async(status:string,text?:string)=>{setBusy(true);const{error}=await supabase.rpc("update_leadership_task",{_task_id:id,_status:status,_message:text||null});setBusy(false);if(error)return toast.error(error.message);setMessage("");toast.success(status==="submitted"?"Work sent for sign-off.":status==="clarification"?"Clarification requested.":"Task updated.");load();};
  const decide=async(decision:string)=>{if(decision==="return"&&!message.trim())return toast.error("Add feedback before returning this work.");setBusy(true);const{error}=await supabase.rpc("decide_leadership_task",{_task_id:id,_decision:decision,_feedback:message||null});setBusy(false);if(error)return toast.error(error.message);setMessage("");toast.success(decision==="accept"?"Work accepted.":decision==="return"?"Work returned with feedback.":"Task cancelled.");load();};
  const addLink=async()=>{let url:URL;try{url=new URL(link);}catch{return toast.error("Enter a complete web link.");}if(!["http:","https:"].includes(url.protocol))return toast.error("Use an http or https link.");const{error}=await supabase.from("leadership_task_evidence").insert({task_id:id,added_by:roles.userId??"",kind:"link",label:url.hostname,url:url.toString()});if(error)return toast.error(error.message);setLink("");load();};
  const upload=async(file:File)=>{if(!roles.userId)return;setBusy(true);const clean=file.name.replace(/[^\w.\-]+/g,"-");const path=`${id}/${crypto.randomUUID()}-${clean}`;const{error:up}=await supabase.storage.from("task-evidence").upload(path,file);if(up){setBusy(false);return toast.error(up.message);}const{error}=await supabase.from("leadership_task_evidence").insert({task_id:id,added_by:roles.userId,kind:"file",label:file.name,storage_path:path});setBusy(false);if(error)return toast.error(error.message);load();};
  const openEvidence=async(item:TaskEvidence)=>{try{const url=await evidenceUrl(item);if(url)window.open(url,"_blank","noopener,noreferrer");}catch(e){toast.error(e instanceof Error?e.message:"Could not open evidence");}};
  return <AppShell eyebrow="Assigned work"><Seo title={`${task.title} — Site 99`} description="Private assigned work." path={`/app/todo/${id}`} noindex/><button onClick={()=>nav("/app/todo")} className="mb-4 flex items-center gap-2 text-xs text-ink-soft hover:text-signal"><ArrowLeft className="h-4 w-4"/>Back to To-Do</button><PageHeader eyebrow={`${task.task_type} · ${task.priority} priority`} title={task.title} lede={task.instruction} actions={<StatusChip value={taskStatusLabel(task.status)} tone={task.status==="accepted"?"success":task.status==="returned"?"warning":"neutral"}/>}/>
    <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_340px]"><main className="space-y-6"><section className="surface rounded-lg p-5"><h2 className="font-semibold">Delivery</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Fact label="Assigned by" value={personName(people,task.assigned_by)}/><Fact label="Assigned to" value={assignees.map((a)=>personName(people,a.user_id)).join(", ")}/><Fact label="Due" value={task.due_at?new Date(task.due_at).toLocaleString():"No deadline"}/><Fact label="Created" value={new Date(task.created_at).toLocaleString()}/></div>{task.private_notes&&<div className="mt-5 rounded-md border border-rule bg-paper-sunken p-4 text-sm"><div className="eyebrow mb-1">Leadership note</div>{task.private_notes}</div>}{task.work_path&&<Link to={task.work_path} className="mt-4 inline-flex items-center gap-2 text-sm text-signal">Open linked work <ExternalLink className="h-4 w-4"/></Link>}</section>
      {(task.submitted_update||task.clarification_request||task.leader_feedback)&&<section className="surface rounded-lg p-5"><h2 className="font-semibold">Updates</h2>{task.clarification_request&&<Update label="Clarification requested" text={task.clarification_request}/>} {task.submitted_update&&<Update label="Submitted report" text={task.submitted_update}/>} {task.leader_feedback&&<Update label="Leadership feedback" text={task.leader_feedback}/>}</section>}
      <section className="surface rounded-lg p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Evidence</h2><span className="text-xs text-ink-faint">{evidence.length} item{evidence.length===1?"":"s"}</span></div><div className="mt-4 grid gap-2">{evidence.map((e)=><Button key={e.id} variant="outline" className="justify-between" onClick={()=>openEvidence(e)}><span className="truncate">{e.label}</span><ExternalLink className="h-4 w-4"/></Button>)}{!evidence.length&&<p className="text-sm text-ink-soft">No files or links yet.</p>}</div>{mine&&!closed&&<div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input className={field} type="url" inputMode="url" value={link} onChange={(e)=>setLink(e.target.value)} placeholder="https://…"/><Button variant="outline" onClick={addLink}><Link2 className="h-4 w-4"/>Add link</Button><label><input className="sr-only" type="file" onChange={(e)=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value="";}}/><span className="inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-md border border-rule px-4 text-sm"><FileUp className="h-4 w-4"/>Upload</span></label></div>}</section>
      {!closed&&(mine||decider)&&<section className="surface rounded-lg p-5"><h2 className="font-semibold">Next action</h2><textarea className={`${field} mt-4 min-h-28`} value={message} onChange={(e)=>setMessage(e.target.value)} placeholder={decider&&task.status==="submitted"?"Feedback for the assignee":"Write your update, report, question, or feedback…"}/><div className="mt-3 flex flex-wrap gap-2">{mine&&task.status==="assigned"&&<Button disabled={busy} onClick={()=>act("in_progress")}><Check className="h-4 w-4"/>Start work</Button>}{mine&&["assigned","in_progress","returned"].includes(task.status)&&<Button disabled={busy} onClick={()=>act("submitted",message)}>Submit for sign-off</Button>}{mine&&<Button variant="outline" disabled={busy} onClick={()=>act("clarification",message)}><MessageSquareWarning className="h-4 w-4"/>Ask for clarity</Button>}{decider&&task.status==="submitted"&&<><Button disabled={busy} onClick={()=>decide("accept")}><Check className="h-4 w-4"/>Accept work</Button><Button variant="outline" disabled={busy} onClick={()=>decide("return")}><RotateCcw className="h-4 w-4"/>Return</Button></>}{decider&&<Button variant="ghost" disabled={busy} onClick={()=>decide("cancel")}><X className="h-4 w-4"/>Cancel task</Button>}</div></section>}</main>
      <aside className="surface h-fit rounded-lg p-5"><h2 className="font-semibold">Activity</h2><div className="mt-4 space-y-4">{activity.map((a)=><div key={a.id} className="border-l border-rule pl-3"><div className="text-sm font-medium">{taskStatusLabel(a.event_type)}</div><div className="text-xs text-ink-soft">{personName(people,a.actor_user_id)} · {new Date(a.created_at).toLocaleString()}</div>{a.detail&&<p className="mt-1 text-xs text-ink-soft">{a.detail}</p>}</div>)}</div></aside></div></AppShell>;
}
function Fact({label,value}:{label:string;value:string}){return <div><div className="eyebrow text-[10px] text-ink-faint">{label}</div><div className="mt-1 text-sm">{value}</div></div>}function Update({label,text}:{label:string;text:string}){return <div className="mt-4"><div className="eyebrow text-[10px] text-ink-faint">{label}</div><p className="mt-1 whitespace-pre-wrap text-sm text-ink-soft">{text}</p></div>}